version: "3"
services:
  metabase-app:
    image: metabase/metabase
    ports:
      - 3001:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - /home/app/metabase-data:/metabase-data
