version: '3.3'

services:
  tomcat:
    image: 'bitnami/tomcat:latest'
    container_name: tomcat
    ports:
      - '8080:8080'
    volumes:
      - 'tomcat_data:/bitnami'
volumes:
  tomcat_data:
    driver: local
