version: '3'

services:
  bitbucket:
    image: "atlassian/bitbucket-server:5.10.2"
    container_name: bitbucket
    ports:
      - "7990:7990"
      - "7999:7999"
    environment:
      - BITBUCKET_HOME=/var/atlassian/application-data/bitbucket/
    volumes:
      - ./bitbucket-data:/var/atlassian/application-data/bitbucket
  db:
    image: postgres:9.6
    container_name: postgresql-bitbucket
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bitbucket
      POSTGRES_USER: bitbucket
      POSTGRES_DB: bitbucket
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data

volumes:
  bitbucket-data:
  postgresql-data:
