version: '3.3'

services:
  db:
    image: webdizz/oracle-xe-11g-sa:latest
    container_name: oracle
    environment:
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "8080:8080"
      - "1521:1521"
    environment:
      - ORACLE_SID=XE
    volumes:
      - .oracle_data:/u01/app/oracle
volumes:
  oracle_data:
