version: '2'
services:
    db:
      image: postgres:9.6
      container_name: db-gogs
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD: gogs
        POSTGRES_USER: gogs
        POSTGRES_DB: gogs
        PGDATA: /var/lib/postgresql/data/pgdata
      volumes:
        - ./db-data:/var/lib/postgresql/data
      networks:
        - gogs
    gogs:
      image: gogs/gogs:latest
      ports:
       - "10022:22"
       - "3000:3000"
      links:
       - db
      environment:
       - "RUN_CROND=true"
      networks:
       - gogs
      volumes:
       - "./gogs-data:/data"
      depends_on:
       - db
networks:
    gogs:
      driver: bridge
volumes:
    db-data:
      driver: local
    gogs-data:
      driver: local
